### ISSUE TITLE
[RFC][BC] builder with and a new behavior

### ISSUE THREAD

**Issue by liuggio** [PUGX/shortid-php#2]
Hi all,
the idea is to have only 2 classes 

The `Generator` with a behavior like:

``` php
$shortId = new Generator()
  ->setLenght(7)
  ->setFactory(/* the ircmaxell/RandomLib factory adapter */)
  ->setSeed(1)
  ->setEasyToRead(false)
  ->getString("ABCDEFG123456") // or getInt?
;
```

and the `ShortId` class would be a Value Object with a __toString() and is possible to create itself directly from the  factory method

``` php
$shortId = ShortId::generate(/*alphabet*/); //it uses the Generator with the default options
```

**Comment by garak** [comment]
Feel free to write a PR.
More details are welcome (maybe on slack?)

**Comment by garak** [comment]
@liuggio see bb7ff262

**Comment by liuggio** [comment]
+1
