### ISSUE TITLE
Is this compatible with php version 5.6.*?

### ISSUE THREAD

**Issue by RodolVelasco** [PUGX/shortid-php#5]
Trying to install it but I have a php version 5.6.*

Here's my log
![image](https://cloud.githubusercontent.com/assets/1563191/26457368/17f82ea6-412d-11e7-9c0c-5df02a9abf8a.png)

**Comment by garak** [comment]
The only available tag compatible with legacy php versions is `v0.1.0`

**Comment by RodolVelasco** [comment]
Thanks.
