### ISSUE TITLE
Why does isValid() accept too long values?

### ISSUE THREAD

**Issue by spackmat** [PUGX/shortid-php#6]
Hi, the current implementation of isValid() accepts too long values as valid ShortIDs. So  `Shortid::isValid('harmful string stuff', 4)` returns `true`.

The code looks like this is on purpose (checks the string to contain a valid ShortID, not is a valid ShortID), but why? And why is the method not called `containsValid` then?

**Comment by garak** [comment]
You're right: I did a wrong assumption about regexp.
I'll add a check for length before the regexp match, it should fix the issue.
Thanks for reporting

**Comment by spackmat** [comment]
Or just change `$ok = preg_match('/(['.$alphabet.']{'.$length.'})/', $value, $matches);` to `$ok = preg_match('/^(['.$alphabet.']{'.$length.'})$/', $value, $matches);` (add ^ and $).
