### ISSUE TITLE
It is just random? not unique?

### ISSUE THREAD

**Issue by charleslxh** [PUGX/shortid-php#7]

**Comment by garak** [comment]
I'm not sure about your question... anyway, the uniqueness is not guaranteed, like any other random system. It's just a matter or probability

**Comment by charleslxh** [comment]
I tested `getMediumStrengthGenerator` of `ircmaxell/random-lib` lib, and I used `5 processes` to generate random string (length => 8), every process generate 100,000 strings, I didn't find any same string in all random strings(500,000).

**Comment by garak** [comment]
Is this enough random for you?

**Comment by charleslxh** [comment]
it's enough in my project, thx!

**Comment by garak** [comment]
You're welcome
