### ISSUE TITLE
Unique id with time

### ISSUE THREAD

**Issue by clementbirkle** [PUGX/shortid-php#8]
Hello, apparently this library is a port of https://github.com/dylang/shortid

The shortid original library create ids with the time to ensure unique ids. I did't see anything similar in this library.

See more here: https://github.com/dylang/shortid/blob/master/lib/build.js

How this library can ensure a unique id ?

**Comment by garak** [comment]
There's no ensured uniqueness. Time doesn't help about that, since you can't assume that IDs are generated in different times.
The real question is the probability of clashing IDs. As already mentioned in #7, you can decrease the chance of clashes by increasing the length of your Shortid.

**Comment by clementbirkle** [comment]
Thank you for your fast response. I thought that the time help to reduce the possibility of collision but apparently not :/
